	tilepal 0, GRAY, GRAY, RED, WATER, WATER, WATER, WATER, GRAY
	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 0, GRAY, GREEN, RED, WATER, WATER, WATER, WATER, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, RED, GRAY, GRAY, RED, WATER, TEXT, TEXT
	tilepal 0, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, GRAY, GRAY, GREEN, TEXT, GRAY, GRAY, TEXT, TEXT
	tilepal 0, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, GRAY, GRAY, GRAY, TEXT, GRAY, GRAY