	tilepal 0, GRAY, GRAY, WATER, WATER, RED, GREEN, GREEN, ROOF
	tilepal 0, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, GRAY, WATER, WATER, RED, BROWN, BROWN, TEXT
	tilepal 0, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, BROWN, WATER
	tilepal 0, GRAY, GRAY, GRAY, RED, ROOF, ROOF, WATER, WATER
	tilepal 0, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, TEXT, TEXT, TEXT, TEXT, ROOF, ROOF, GRAY, GRAY
	tilepal 0, PRIORITY_GREEN, PRIORITY_GREEN, GREEN, GREEN, GREEN, GREEN, WATER, WATER
	tilepal 0, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, WATER, GRAY, GRAY
	tilepal 0, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, PRIORITY_ROOF, PRIORITY_ROOF, PRIORITY_ROOF, PRIORITY_ROOF, PRIORITY_ROOF, GREEN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, ROOF, TEXT, ROOF